version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  reviewers:
  - michaelgracious
  assignees:
  - michaelgracious
